IF(CONFIG_JET_PORT)
	SET(CONFIG_JET_PORT ${CONFIG_JET_PORT} CACHE STRING "" FORCE)
ELSE()
	SET(CONFIG_JET_PORT 11122)
ENDIF()

IF(CONFIG_JETWS_PORT)
        SET(CONFIG_JETWS_PORT ${CONFIG_JETWS_PORT} CACHE STRING "" FORCE)
ELSE()
        SET(CONFIG_JETWS_PORT 11123)
ENDIF()

IF(CONFIG_UDS_PATH)
        SET(CONFIG_UDS_PATH ${CONFIG_UDS_PATH} CACHE STRING "" FORCE)
ELSE()
        SET(CONFIG_UDS_PATH "/tmp/jetd.sock")
ENDIF()


IF(CONFIG_LISTEN_BACKLOG)
	SET(CONFIG_LISTEN_BACKLOG ${CONFIG_LISTEN_BACKLOG} CACHE STRING "" FORCE)
ELSE()
	SET(CONFIG_LISTEN_BACKLOG 40)
ENDIF()

# It is somehow beneficial if this size is 32 bit aligned.
IF(CONFIG_MAX_MESSAGE_SIZE)
	SET(CONFIG_MAX_MESSAGE_SIZE ${CONFIG_MAX_MESSAGE_SIZE} CACHE STRING "" FORCE)
ELSE()
	SET(CONFIG_MAX_MESSAGE_SIZE 512)
ENDIF()

IF(CONFIG_MAX_WRITE_BUFFER_SIZE)
	SET(CONFIG_MAX_WRITE_BUFFER_SIZE ${CONFIG_MAX_WRITE_BUFFER_SIZE} CACHE STRING "" FORCE)
ELSE()
	SET(CONFIG_MAX_WRITE_BUFFER_SIZE 5120)
ENDIF()

# This parameter configures the maximum amount of states that can be
# handled in a jet. The number of states is 2^ELEMENT_TABLE_ORDER.
IF(CONFIG_ELEMENT_TABLE_ORDER)
	SET(CONFIG_ELEMENT_TABLE_ORDER ${CONFIG_ELEMENT_TABLE_ORDER} CACHE STRING "" FORCE)
ELSE()
	SET(CONFIG_ELEMENT_TABLE_ORDER 13)
ENDIF()

# This parameter configures the maximum ongoing routed messages per
# peer.

IF(CONFIG_ROUTING_TABLE_ORDER)
	SET(CONFIG_ROUTING_TABLE_ORDER ${CONFIG_ROUTING_TABLE_ORDER} CACHE STRING "" FORCE)
ELSE()
	SET(CONFIG_ROUTING_TABLE_ORDER 6)
ENDIF()

IF(CONFIG_MAX_EPOLL_EVENTS)
	SET(CONFIG_MAX_EPOLL_EVENTS ${CONFIG_MAX_EPOLL_EVENTS} CACHE STRING "" FORCE)
ELSE()
	SET(CONFIG_MAX_EPOLL_EVENTS 10)
ENDIF()

IF(CONFIG_UDS_FILE)
	SET(CONFIG_UDS_FILE ${CONFIG_UDS_FILE} CACHE STRING "" FORCE)
ELSE()
	SET(CONFIG_UDS_FILE "/var/run/jet.socket")
ENDIF()

IF(WEBSOCKET_PATH)
        SET(WEBSOCKET_PATH ${WEBSOCKET_PATH} CACHE STRING "" FORCE)
ELSE()
        SET(WEBSOCKET_PATH "/api/jet/")
ENDIF()


IF(CONFIG_INITIAL_FETCH_TABLE_SIZE)
	SET(CONFIG_INITIAL_FETCH_TABLE_SIZE ${CONFIG_INITIAL_FETCH_TABLE_SIZE} CACHE STRING "" FORCE)
ELSE()
	SET(CONFIG_INITIAL_FETCH_TABLE_SIZE 4)
ENDIF()

IF(CONFIG_ROUTED_MESSAGES_TIMEOUT)
	SET(CONFIG_ROUTED_MESSAGES_TIMEOUT ${CONFIG_ROUTED_MESSAGES_TIMEOUT} CACHE STRING "" FORCE)
ELSE()
	SET(CONFIG_ROUTED_MESSAGES_TIMEOUT 5.0)
ENDIF()

IF(CONFIG_MAX_NUMBERS_OF_MATCHERS_IN_FETCH)
	SET(CONFIG_MAX_NUMBERS_OF_MATCHERS_IN_FETCH ${CONFIG_MAX_NUMBERS_OF_MATCHERS_IN_FETCH} CACHE STRING "" FORCE)
ELSE()
	SET(CONFIG_MAX_NUMBERS_OF_MATCHERS_IN_FETCH 12)
ENDIF()

IF(CONFIG_ALLOW_ADD_ONLY_FROM_LOCALHOST)
	SET(CONFIG_ALLOW_ADD_ONLY_FROM_LOCALHOST ${CONFIG_ALLOW_ADD_ONLY_FROM_LOCALHOST} CACHE STRING "" FORCE)
ELSE()
	SET(CONFIG_ALLOW_ADD_ONLY_FROM_LOCALHOST false)
ENDIF()

IF(CONFIG_MAX_HEAPSIZE_IN_KBYTE)
	SET(CONFIG_MAX_HEAPSIZE_IN_KBYTE ${CONFIG_MAX_HEAPSIZE_IN_KBYTE} CACHE STRING "" FORCE)
ELSE()
	SET(CONFIG_MAX_HEAPSIZE_IN_KBYTE 20480)
ENDIF()
