# this one is important
SET(CMAKE_SYSTEM_NAME Linux)

SET(CMAKE_C_COMPILER gcc)
SET(CMAKE_CXX_COMPILER g++)
SET(CMAKE_AR gcc-ar CACHE FILEPATH "Archiver")
SET(CMAKE_RANLIB gcc-ranlib CACHE FILEPATH "Ranlib")

